# -*- coding: utf-8 -*-
"""Assignment3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ur8IGTOilMhGIRF_pUjZpYOqQ1PxaSuQ
"""



"""# **List**"""

num_list : list [int]=[1,2,3,4,5]
num_list.append(6)
print(num_list)

numbers  = [1,2,3]
numbers.extend([4,5,6])
print(numbers)

lang_list = ["Java", "C++", "Javascript", "Ruby"]
lang_list.insert(2,"Python")
print(lang_list)

num_list = [10,20,30,10,40]
num_list.remove(num_list[0])
print(num_list)

num_list = [100, 200, 300, 400]
num_list.pop()
print(num_list)

num_list = [5, 10, 5, 20, 5, 30]

print(num_list.count(5))

"""**Sort**"""

numbers_list = [9, 1, 8, 3, 5]
numbers_list.sort()
print(numbers_list)
numbers_list.sort(reverse=True)
print(numbers_list)

fruits = ["apple", "banana", "cherry"]
fruits.reverse()
print(fruits)

list1 = [1, 2, 3, 4, 5]
print(list1)
list2 = list1
list2.append(6)
print(list2)

list = ["hello", "world", "python"]
list.clear()
print(list)

"""# **Tuples**








"""

fruits = ("apple", "banana", "mango", "grapes", "guava")
print(fruits[2])

num_tuple = (10, 20, 30, 40, 50)
num_list = list(num_tuple)
print(num_list)
num_list.remove(num_list[2])
num_tuple = tuple(num_list)
print(num_tuple)

"""Tuple is immutable so we can not append any element in tuple.
Indirectly we first convert tuple into list then we are able to make changes in it.
"""

tup1 =(100)
tup2 =(200)
tup3 = (300)
print(tup1,tup2,tup3)

tpl=(7,1,7,3,7,5)
print(tpl.count(7))

"""Problems"""

lst = [4, 7, 12, 35, 60, 93]

def check(lst):
    new_list = []
    for i in lst:
        if i % 2 != 0:
            new_list.append(i)
    return new_list

print(check(lst))

lst = [4, 7, 12, 35, 60, 93]

def check(lst):
    return [i for i in lst if i % 2 != 0]

print(check(lst))

def sorting(lst):

  new_list = []
  for i in range(len(lst)):   # to process each element in list
    max_val = max(lst)        # find maximum element
    new_list.append(max_val)  # append maximum element in new list
    lst.remove(max_val)       # remove maximum element from original list
  return new_list

numbers = [12, 4, 60, 93, 7, 35]
descending_order = sorting(numbers)
print(descending_order)

numbers = [1, 1, 2, 2, 3, 3, 4, 5]
unique_elements= list(set(numbers))
print(unique_elements)

names : tuple =("Alice", "Bob", "Charlie", "Alice", "David")
name_list= list(names)
name_list.remove("Alice")
names = tuple(name_list)
print(names)